import { getMedia, getReports } from "@/lib/deals/store";
import { Card, Pill, SectionTitle } from "../ui";
import { UploadButton } from "../UploadButton";

export const dynamic = "force-dynamic";

const KEY_DOCS = [
  { name: "Contract to Purchase", note: "executed 07/31/26" },
  { name: "Defect Notice", note: "delivered 08/07/26" },
  { name: "Inspection Report", note: "AA Home Inspection, 08/04/26" },
  { name: "Radon Report", note: "13.6 pCi/L avg" },
  { name: "Extension Addendum #1", note: "signed 08/09/26" },
  { name: "Erie Insurance Policy", note: "flat $1,000 deductible" },
  { name: "Rocket Mortgage Payoff", note: "banded — verify fresh before close" },
];

export default async function DocumentsPage() {
  const [media, reports] = await Promise.all([getMedia(), getReports()]);
  const docs = media.filter((m) => m.kind === "document");

  return (
    <div className="space-y-6">
      <Card className="p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <SectionTitle>Document vault</SectionTitle>
            <p className="text-sm text-neutral-500 dark:text-neutral-400">
              Store quotes, receipts, warranties, and any deal paperwork in one
              place.
            </p>
          </div>
          <UploadButton kind="document" label="Upload document" />
        </div>

        {docs.length ? (
          <ul className="mt-4 divide-y divide-[#f4f6f8] dark:divide-[#182530]">
            {docs.map((d) => (
              <li
                key={d.id}
                className="flex items-center justify-between gap-3 py-2 text-sm"
              >
                <a
                  href={d.url}
                  target="_blank"
                  rel="noreferrer"
                  className="text-[#003a70] hover:underline dark:text-[#c6dae7]"
                >
                  {d.label}
                </a>
                <span className="text-xs text-neutral-400">
                  {new Date(d.uploadedAt).toLocaleDateString()}
                </span>
              </li>
            ))}
          </ul>
        ) : (
          <p className="mt-4 text-sm text-neutral-400">
            No documents uploaded yet.
          </p>
        )}
      </Card>

      <Card className="p-5">
        <SectionTitle hint="generated by the deal room">
          Reports
        </SectionTitle>
        {reports.length ? (
          <ul className="space-y-2">
            {reports.map((r) => (
              <li key={r.name} className="text-sm">
                <a
                  href={r.url}
                  target="_blank"
                  rel="noreferrer"
                  className="text-[#003a70] hover:underline dark:text-[#c6dae7]"
                >
                  {r.label}
                </a>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-sm text-neutral-400">No reports generated yet.</p>
        )}
      </Card>

      <Card className="p-5">
        <SectionTitle hint="on file in the deal room">
          Key source documents
        </SectionTitle>
        <ul className="grid gap-2 sm:grid-cols-2">
          {KEY_DOCS.map((d) => (
            <li
              key={d.name}
              className="flex items-center justify-between gap-2 rounded-lg border border-[#f4f6f8] px-3 py-2 text-sm dark:border-[#182530]"
            >
              <span className="text-neutral-700 dark:text-neutral-300">
                {d.name}
              </span>
              <Pill>{d.note}</Pill>
            </li>
          ))}
        </ul>
      </Card>
    </div>
  );
}
